services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:4001:4001"
    environment:
      NODE_ENV: development