name: nexa-app

services:
  db:
    image: postgres:16-alpine  # 16 est stable & rapide en 2026
    restart: unless-stopped
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 8
    # ports: ["5433:5432"]   # décommente uniquement si besoin d'accès pgAdmin/local


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production          # on build que le stage prod par défaut
    restart: unless-stopped
    expose:
      - "4001"
    environment:
      NODE_ENV:       production
      PORT:           4000
      DOCKER_ENV:     true
      DATABASE_URL:   postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET:     ${JWT_SECRET:?required}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      BCRYPT_SALT:    ${BCRYPT_SALT}
      # Ajoute les autres (Cloudinary, email…) au fur et à mesure
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Ecommerce
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    # ports:
    #   - "3000:80"          # décommente en dev si tu veux tester sans reverse-proxy

volumes:
  pgdata: